name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  vapor-ci:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Swift packages
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build project
        run: swift build

      - name: Run tests
        run: swift test --enable-test-discovery
        
      - name: Build for release
        run: swift build -c release
